version: 0.2

env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      python: 3.8
      ruby: latest
    commands:
      # Upgrade pip to the latest version
      - pip install --upgrade pip

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

      # Install linter for CloudFormation template
      - pip install cfn-lint

      # Install cfn-nag
      - gem install cfn-nag

      # Install requirements
      - pip install -r ./requirements.txt

  pre_build:
    commands:
      - cfn-lint -t ./template.yaml
      - cfn_nag_scan -i . -t template.yaml

  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template-file ./template.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      - printf '{"Parameters":{"DistributionIdDev":"%s","DistributionIdQa":"%s","DistributionIdProd":"%s"}}' "$DISTRIBUTION_ID_DEV" "$DISTRIBUTION_ID_QA" "$DISTRIBUTION_ID_PROD" > config.json

artifacts:
  files:
    - template-export.yml
    - config.json