AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "SAM Template for codetekt helper functions"
    
Resources:
  CreateInvalidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.create_invalidation
      Runtime: python3.8
      Role: !GetAtt CreateInvalidationRole.Arn
  CreateInvalidationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: CreateInvalidationRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                  - codepipeline:PutJobFailureResult
                  - codepipeline:PutJobSuccessResult
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource: '*'

Outputs:
  CreateInvalidationFunction:
    Description: "Create Invalidation Function"
    Value: !GetAtt CreateInvalidationFunction.Arn
