AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "SAM Template for DetektivKollektiv Helper"

Parameters:
  DistributionIdDev:
    Type: String
  DistributionIdQa:
    Type: String
  DistributionIdProd:
    Type: String
    
Resources:
  CreateInvalidationFunctionDev:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.create_invalidation
      Runtime: python3.8
      Environment:
        Variables:
          DISTRIBUTION_ID: 
            Ref: DistributionIdDev
  CreateInvalidationFunctionQa:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.create_invalidation
      Runtime: python3.8
      Environment:
        Variables:
          DISTRIBUTION_ID: 
            Ref: DistributionIdQa
  CreateInvalidationFunctionProd:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.create_invalidation
      Runtime: python3.8
      Environment:
        Variables:
          DISTRIBUTION_ID: 
            Ref: DistributionIdProd
  CreateInvalidationPolicy:
    Type: AWS::IAM::Policy
    Properties:
        Roles:
            - !GetAtt CreateInvalidationFunctionDevRole.Arn
            - !GetAtt CreateInvalidationFunctionQaRole.Arn
            - !GetAtt CreateInvalidationFunctionProdRole.Arn
        PolicyDocument: >
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "CreateInvalidationPolicy",
                "Effect": "Allow",
                "Action": [
                  "cloudfront:CreateInvalidation",
                  "codepipeline:PutJobFailureResult",
                  "codepipeline:PutJobSuccessResult",
                  "logs:PutLogEvents",
                  "logs:CreateLogStream",
                  "logs:CreateLogGroup"
                ],
                "Resource": "*"
              }
            ]
          }
    
        PolicyName: CreateInvalidationPolicy


Outputs:
  CreateInvalidationFunctionDev:
    Description: "Create DEV Invalidation Function"
    Value: !GetAtt CreateInvalidationFunctionDev.Arn
  CreateInvalidationFunctionQa:
    Description: "Create QA Invalidation Function"
    Value: !GetAtt CreateInvalidationFunctionQa.Arn
  CreateInvalidationFunctionProd:
    Description: "Create PROD Invalidation Function"
    Value: !GetAtt CreateInvalidationFunctionProd.Arn
